spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**
        - id: r3
          uri: http://localhost:8083/
          predicates:
            - Path=/paniers/**
        - id: r4
          uri: http://localhost:8084/
          predicates:
            - Path=/paiements/**
